/*
 * PanelCadastro.java
 *
 * Created on 25 de Julho de 2007, 10:54
 */

package br.com.codigocerto.swing.formularios;

import br.com.codigocerto.conversores.ConversorTipos;
import java.awt.event.KeyEvent;
import javax.swing.JPanel;

/**
 *
 * @author  lis
 */
public class PanelCadastro extends javax.swing.JPanel {
    
    private final String MASCARA_CODIGO = "######";
    private final int TAMANHO_CAMPO_NOME = 80;
    private PanelEntradaCadastro _panelEntrada;
    
    /**
     * Creates new form PanelCadastro
     */
    public PanelCadastro() {
        initComponents();
        configurar();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabelCodigo = new javax.swing.JLabel();
        ccTextFormatadoCodigo = new br.com.codigocerto.swing.CCTextFormatado();
        jLabelNome = new javax.swing.JLabel();
        ccTextFormatadoNome = new br.com.codigocerto.swing.CCTextFormatado();
        jTabbedPanePrincipal = new javax.swing.JTabbedPane();

        jLabelCodigo.setText("C\u00f3digo");

        ccTextFormatadoCodigo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ccTextFormatadoCodigo.setDisabledTextColor(new java.awt.Color(102, 102, 255));
        ccTextFormatadoCodigo.setName("Id");
        ccTextFormatadoCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ccTextFormatadoCodigoFocusLost(evt);
            }
        });
        ccTextFormatadoCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ccTextFormatadoCodigoKeyReleased(evt);
            }
        });

        jLabelNome.setText("Nome");

        ccTextFormatadoNome.setName("Nome");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPanePrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelNome)
                            .addComponent(jLabelCodigo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ccTextFormatadoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ccTextFormatadoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodigo)
                    .addComponent(ccTextFormatadoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(ccTextFormatadoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPanePrincipal)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ccTextFormatadoCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ccTextFormatadoCodigoKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_F3) {
            UICadastro cadastro = (UICadastro) _panelEntrada.getOrigem();
            cadastro.efetuarPesquisaCadastro();
        }
    }//GEN-LAST:event_ccTextFormatadoCodigoKeyReleased

    private void ccTextFormatadoCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ccTextFormatadoCodigoFocusLost
        if (ccTextFormatadoCodigo.isAlterado()) {
            UIEntradaDados cadastro = _panelEntrada.getOrigem();
            long id = getId();
            if ( ! cadastro.isCadastrado(id)) {
                _panelEntrada.setNovo(true);
                setId(id);
            } else {
                _panelEntrada.setAlterado(false);
                cadastro.exibirDados();
                ccTextFormatadoNome.requestFocusInWindow();
            }
        }
    }//GEN-LAST:event_ccTextFormatadoCodigoFocusLost
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected br.com.codigocerto.swing.CCTextFormatado ccTextFormatadoCodigo;
    protected br.com.codigocerto.swing.CCTextFormatado ccTextFormatadoNome;
    protected javax.swing.JLabel jLabelCodigo;
    protected javax.swing.JLabel jLabelNome;
    protected javax.swing.JTabbedPane jTabbedPanePrincipal;
    // End of variables declaration//GEN-END:variables

    /**
     *Adiciona painel
     *@param string com titulo do painel
     *@param JPanel painel para a area de abas
     */
    public void addPainel(String titulo, JPanel painel) {
        jTabbedPanePrincipal.addTab(titulo, painel);
        if ( ! jTabbedPanePrincipal.isVisible()) {
            jTabbedPanePrincipal.setVisible(true);
        }
        validate();
    }
    
    /**
     *Muda foco para controle do campo codigo
     */
    public void focarCodigo() {
        ccTextFormatadoCodigo.requestFocusInWindow();
    }
    
    /**
     *Insere conteudo no campo de id (codigo)
     *@param long com codigo
     */
    public void setId(long id) {
       ConversorTipos conversor = new ConversorTipos();
       conversor.setValorBase(id); 
       ccTextFormatadoCodigo.setText(conversor.getString()); 
    }
    
    /**
     *Informa conteudo do campo id (codigo)
     *@return long com codigo
     */
    public long getId() {
        long codigo = 0L;
        
        String textoId = ccTextFormatadoCodigo.getText();
        if ( ! textoId.equals("")) {
            ConversorTipos conversor = new ConversorTipos();
            conversor.setValorBase(textoId);
            codigo = conversor.getLong();
        }
        
        return codigo;
    }

    /**
     *Insere conteudo no campo de nome
     *@param string com nome
     */
    public void setNome(String nome) {
        if (nome != null) {
            ccTextFormatadoNome.setText(nome); 
        }
    }

    /**
     *Configura estado de alteracao
     *@param boolean com estado
     */
    public void setAlterado(boolean alterado) {
        ccTextFormatadoCodigo.setEnabled( ! alterado);
    }
    
    /**
     *Configura estado de Novo cadastro
     *@param boolean com estado
     */
    public void setNovo(boolean novo) {
        ccTextFormatadoCodigo.setEnabled( ! novo);
        ccTextFormatadoNome.requestFocusInWindow();
    }
    
    /**
     * Configura painel de entrada que invocou este painel de cadastro
     * @param painel 
     */
    public void setEntrada(PanelEntradaCadastro painel) {
        _panelEntrada = painel;
    }
    
    private void configurar() {
        jTabbedPanePrincipal.setVisible(false);
        ccTextFormatadoCodigo.setMascaraEdicao(MASCARA_CODIGO);
        StringBuilder mascaraNome = new StringBuilder(TAMANHO_CAMPO_NOME);
        for (int i = 0; i < TAMANHO_CAMPO_NOME; i++) {
            mascaraNome.append('*');
        }
        ccTextFormatadoNome.setMascaraEdicao(mascaraNome.toString());
        ccTextFormatadoNome.setMaiusculas(true);
    }
    
}
