/*
 * CCAreaTrabalho.java
 *
 * Created on 29 de Maio de 2007, 09:07
 */

package br.com.codigocerto.swing;

/**
 *
 * @author  lis
 */
public class CCAreaTrabalho extends javax.swing.JPanel {
    
    /** Creates new form CCAreaTrabalho */
    public CCAreaTrabalho() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Código Gerado ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jToolBarAreaTrabalho = new javax.swing.JToolBar();

        setBackground(java.awt.Color.gray);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBarAreaTrabalho, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBarAreaTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(374, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Declaração de variáveis - não modifique//GEN-BEGIN:variables
    private javax.swing.JToolBar jToolBarAreaTrabalho;
    // Fim da declaração de variáveis//GEN-END:variables
    
}
