/*
 * PanelConsultaJasper.java
 *
 * Created on 1 de Julho de 2008, 18:18
 */

package br.com.codigocerto.swing.formularios;

import java.awt.event.ActionListener;
import javax.swing.GroupLayout;
import javax.swing.JPanel;

/**
 *
 * @author  lis
 */
public class PanelConsultaJasper extends javax.swing.JPanel {
    
    private UIConsultaJasper _consulta;

    /** Creates new form PanelConsultaJasper */
    public PanelConsultaJasper() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barra = new br.com.codigocerto.swing.barras.BarraConsulta();
        jPanelMovimento = new javax.swing.JPanel();

        barra.setFloatable(false);

        javax.swing.GroupLayout jPanelMovimentoLayout = new javax.swing.GroupLayout(jPanelMovimento);
        jPanelMovimento.setLayout(jPanelMovimentoLayout);
        jPanelMovimentoLayout.setHorizontalGroup(
            jPanelMovimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 317, Short.MAX_VALUE)
        );
        jPanelMovimentoLayout.setVerticalGroup(
            jPanelMovimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 137, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barra, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
            .addComponent(jPanelMovimento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(barra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelMovimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.com.codigocerto.swing.barras.BarraConsulta barra;
    private javax.swing.JPanel jPanelMovimento;
    // End of variables declaration//GEN-END:variables
    
    /**
     *Configura acao para botao fechar
     *@param acao para fechar formulario
     */
    public void setAcaoFechar(ActionListener acao) {
        barra.setAcaoFechar(acao);
    }

    /**
     *Configura acao para botao exibir consulta
     *@param acao para gerar consulta
     */
    public void setAcaoExibirConsulta(ActionListener acao) {
        barra.setAcaoExibirConsulta(acao);
    }

    /**
     *Configura acao para botao imprimir consulta
     *@param acao para imprimir consulta
     */
    public void setAcaoImprimirConsulta(ActionListener acao) {
        barra.setAcaoImprimirConsulta(acao);
    }

    /**
     * Adiciona painel com objetos da consulta
     * @param painel 
     */
    public void addPainelConsulta(JPanel painel) {
        GroupLayout layout = (GroupLayout) jPanelMovimento.getLayout();
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                )
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                )
        );
    }

    /***
     * Configurar origem
     * @param consulta
     */
    public void setOrigem(UIConsultaJasper consulta) {
        _consulta = consulta;
    }
    
}///~